name: shell commands
on: [workflow_dispatch]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@v3
            - name: echo string
              run: echo "hello world"
            - name: multi string
              run: |
                node -v
                npm -v
